### ISSUE TITLE
Deprecation of / for division

### ISSUE THREAD

**Issue by justinwyllie** [timoludwig/flagpack-dart-sass#1]
"Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0."

The / sign is used in flagpack.scss. Can I just ask; are you planning to address this?

**Comment by timoludwig** [comment]
@justinwyllie Sorry for not answering earlier.
I'm not sure whether I understand your issue. I thought I eliminated the deprecation warnings in 952d7c757dcb40a6fa38ba83a4b4e96252a109fc.
Which version of this package are you using and how are you installing it? Maybe you use the original package [flagpack](https://www.npmjs.com/package/flagpack) and not my fork [flagpack-dart-sass](https://www.npmjs.com/package/flagpack-dart-sass)? Or am I missing something here?

**Comment by justinwyllie** [comment]
Hi @timoludwig 
So sorry. You are completely right. I was using the original flagpack. I changed to use your forked version and now it all works without the warnings.
Thank you so much and sorry to be a nuisance.

**Comment by timoludwig** [comment]
@justinwyllie alright, no worries :slightly_smiling_face:
